@baseUrl = http://localhost:3000

### Try to login an unknow user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"unknown",
    "password":"unknown"
}

### Login the default user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"user1",
    "password":"user1"
}


### Create random user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"user2",
    "password":"user2"
}

### Login random user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"hello",
    "password":"hello"
}

### Logout any user
GET {{baseUrl}}/auths/logout