@baseUrl = http://localhost:3000

### Try to login an unknow user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"unknown",
    "password":"unknown"
}

### Login the default user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"hi",
    "password":"hi"
}


### Create the manager user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"hi",
    "password":"hi"
}

### Login the manager user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"manager",
    "password":"manager"
}
