@baseUrl = http://localhost:3000

### Read all users
GET {{baseUrl}}/users
### Read all users ordered by highscore
GET {{baseUrl}}/users/?order=score
### Get one user by its id 
GET {{baseUrl}}/users/user?id=1

### get one user by its username
GET {{baseUrl}}/users/user?username=Aikyu


### Update balance of the user
PATCH {{baseUrl}}/users/balance?username=Aikyu
Content-Type: application/json

{
    "balance":"200",
    "operator": "-"
}

### Update user's highscore
PATCH {{baseUrl}}/users/highscore?username=Aikyu
Content-Type: application/json

{
    "highscore": 32222
}

### get random animal
GET {{baseUrl}}/animals

### get info on animal by name
GET https://api.api-ninjas.com/v1/animals?name=Dolphin
X-Api-Key: sDkpQuiIx0EY/GZKXSCbtA==O6Tm10FAA9ee9GZu