@baseUrl = http://localhost:3000

### Read all users
GET {{baseUrl}}/users
### Read all users ordered by highscore
GET {{baseUrl}}/users/?order=score
### Get one user by its id 
GET {{baseUrl}}/users/user?id=1

### get one user by its username
GET {{baseUrl}}/users/user?username=manager


### Update balance of the user
PATCH {{baseUrl}}/users/balance/1
Content-Type: application/json

{
    "balance":"200",
    "operator": "-"
}

### Update user's highscore
PATCH {{baseUrl}}/users/highscore/2
Content-Type: application/json

{
    "highscore": 32222
}

### get random animal
GET {{baseUrl}}/animals